version: "3"
services:
  web:
    build:
      context: ./conf/nginx
      dockerfile: Dockerfile
    ports:
        - "8181:9191"
    volumes:
        - ./src:/var/www/html
        - ./log/nginx:/var/log/nginx/
        - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
        - ./conf/nginx/default.conf:/etc/nginx/conf.d/default.conf

  php-fpm:
    build:
      context: ./conf/php
      dockerfile: Dockerfile
    # user: "${UID}:${GID}"
    ports:
        - "8080:8080"
    volumes:
      - ./src:/var/www/html
      - ./log/php:/var/log/php/
    extra_hosts:
      - host.docker.internal:host-gateway

  mysql:
    image: mysql:8.0.26
    ports:
      - "3306:3306"
    environment: 
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mysql
      - PMA_USER=${PMA_USER}
      - PMA_PASSWORD=${PMA_PASSWORD}
      - UPLOAD_LIMIT=${UPLOAD_LIMIT}